version: 2
jobs:
  build:
    working_directory: ~/build
    branches:
      only:
        - source
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout

      - run: git clone https://github.com/FCP-INDI/C-PAC /home/circleci/code

      - restore_cache:
          keys:
          - cpac-requirements-{{ checksum "/home/circleci/code/requirements.txt" }}

      - run: pipenv install -r /home/circleci/code/requirements.txt
      - run: pipenv install sphinx

      - save_cache:
          paths:
            - ".venv"
          key: cpac-requirements-{{ checksum "/home/circleci/code/requirements.txt" }}
          
      - run: pipenv install sphinx /home/circleci/code
      - run: pipenv run bin/build