version: 2
jobs:
  build:
    working_directory: /build
    branches:
      only:
        - source
    docker:
      - image: fcpindi/c-pac:latest
    steps:
      - checkout
      - run: pip install sphinx
      - run: ./bin/build

      - run:
          name: Configure Github
          command: |
            git config user.email "ci-build@fcp-indi.github.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            git clone --single-branch --branch gh-pages git@github.com:FCP-INDI/fcp-indi.github.com.git /tmp/repo
            rsync -rtv ./ /tmp/repo/ --exclude '.git'
            cd /tmp/repo
            git rm .gitignore
            git add .
            git commit -m "updates"
            git push -f origin gh-pages
            cd -